<script setup lang="ts">
import { ArrowUpRight, Baby, Cross, HeartPulse, Leaf, ShieldPlus, Sparkles } from '@lucide/vue'
import type { StoreCategory } from '#shared/types/storefront'
defineProps<{ categories: StoreCategory[] }>()
const icons = [HeartPulse, Sparkles, Baby, Leaf, ShieldPlus, Cross]
</script>

<template>
  <main class="categories-page"><div class="categories-heading"><span>Todos os cuidados</span><h1>O que você precisa hoje?</h1><p>Navegue por necessidade e encontre produtos para cada momento da sua rotina.</p></div><div v-if="categories.length" class="categories-list"><NuxtLink v-for="(category,index) in categories" :key="category.id" :to="`/categoria/${category.slug}`"><span class="number">{{ String(index+1).padStart(2,'0') }}</span><div class="category-icon"><component :is="icons[index % icons.length]" :size="27"/></div><div><h2>{{ category.name }}</h2><p>{{ category.description || 'Produtos selecionados para um cuidado simples e seguro.' }}</p></div><ArrowUpRight class="arrow" :size="24"/></NuxtLink></div><div v-else class="empty">As categorias da farmácia aparecerão aqui em breve.</div></main>
</template>

<style scoped>
.categories-page{max-width:1380px;margin:auto;padding:75px 32px}.categories-heading span{color:var(--sf-primary);font:800 10px ui-monospace,monospace;letter-spacing:.15em;text-transform:uppercase}.categories-heading h1{max-width:920px;margin:13px 0 20px;font-family:"Trebuchet MS",sans-serif;font-size:clamp(54px,7.5vw,104px);line-height:.87;letter-spacing:-.075em}.categories-heading p{max-width:600px;color:#667c78;line-height:1.65}.categories-list{display:grid;grid-template-columns:1fr 1fr;margin-top:75px;border-top:1px solid #d7e4e0}.categories-list>a{position:relative;display:grid;grid-template-columns:36px 54px 1fr auto;align-items:start;gap:15px;min-height:220px;padding:28px;border-bottom:1px solid #d7e4e0;color:var(--sf-ink);text-decoration:none}.categories-list>a:nth-child(odd){border-right:1px solid #d7e4e0}.number{padding-top:13px;color:#7b908b;font:700 9px ui-monospace,monospace}.category-icon{display:grid;width:50px;height:50px;place-items:center;border-radius:14px 14px 14px 4px;background:#dff4ec;color:var(--sf-primary)}.categories-list>a:nth-child(4n+2) .category-icon{background:#e8f1ff;color:#315f97}.categories-list>a:nth-child(4n+3) .category-icon{background:#fff1df;color:#a66023}.categories-list h2{margin:8px 0 10px;font-family:"Trebuchet MS",sans-serif;font-size:29px;letter-spacing:-.045em}.categories-list p{max-width:38ch;margin:0;color:#6d817d;font-size:12px;line-height:1.55}.arrow{margin-top:13px;color:var(--sf-primary);transition:transform .2s}.categories-list>a:hover .arrow{transform:translate(3px,-3px)}.empty{margin-top:65px;padding:70px;border:1px dashed #bdcec9;border-radius:15px;text-align:center;color:#6d817d}@media(max-width:800px){.categories-list{grid-template-columns:1fr}.categories-list>a:nth-child(odd){border-right:0}}@media(max-width:560px){.categories-page{padding:55px 16px}.categories-heading h1{font-size:56px}.categories-list{margin-top:50px}.categories-list>a{grid-template-columns:48px 1fr auto;min-height:180px;padding:22px 5px}.number{display:none}.category-icon{width:44px;height:44px}.categories-list h2{margin-top:5px;font-size:24px}}
</style>
