import type { StorefrontTemplateBranding } from '#shared/types/template'

export const defaultBranding: StorefrontTemplateBranding = {
  logo_url: null,
  favicon_url: null,
  hero_image_url: null,
  primary_color: '#12372a',
  secondary_color: '#1f6b4f',
  accent_color: '#dff36a',
  font_family: 'Aptos',
  hero_title: 'Tudo para a sua rotina.',
  hero_subtitle: 'Produtos selecionados e ofertas para comprar com praticidade.',
  featured_title: 'Destaques da loja',
  show_newsletter: true,
  header_message: '',
  contact_phone: '',
  service_hours: '',
  hero_eyebrow: '',
  hero_cta_label: 'Ver produtos',
  categories_title: 'Categorias',
  promo_primary_title: '',
  promo_primary_text: '',
  promo_secondary_title: '',
  promo_secondary_text: '',
  promo_tertiary_title: '',
  promo_tertiary_text: '',
  offers_callout_title: '',
  offers_callout_text: '',
  popular_title: '',
  newsletter_eyebrow: '',
  newsletter_title: '',
  newsletter_text: '',
  newsletter_button_label: '',
  footer_tagline: '',
  footer_description: '',
}
