<script setup lang="ts">
import { Heart, Plus } from '@lucide/vue'
import type { StoreProduct, StorefrontPayload } from '#shared/types/storefront'
const props = defineProps<{ product: StoreProduct, storefront: StorefrontPayload }>()
const { money, productImage, usePlaceholder, discount } = useStorefrontCatalog(props.storefront)
</script>

<template>
  <article class="product-card"><div class="product-visual"><NuxtLink :to="`/produto/${product.slug}`"><img v-if="productImage(product)" :src="productImage(product)!" :alt="product.name" loading="lazy" @error="usePlaceholder"><img v-else src="/images/placeholders/product-default.png" alt="Imagem ilustrativa do produto" loading="lazy"></NuxtLink><span v-if="discount(product)" class="discount">Economize {{ discount(product) }}%</span><button class="heart" type="button" aria-label="Adicionar aos favoritos"><Heart :size="17"/></button></div><div class="product-copy"><span>{{ product.categories[0]?.name || 'Cuidado diário' }}</span><NuxtLink :to="`/produto/${product.slug}`"><h3>{{ product.name }}</h3></NuxtLink><small v-if="product.excerpt">{{ product.excerpt }}</small><div class="price-row"><div><s v-if="product.original_price && product.original_price > product.price">{{ money(product.original_price) }}</s><strong>{{ money(product.price) }}</strong><em>à vista</em></div><button type="button" disabled aria-label="Adicionar à cesta"><Plus :size="20"/></button></div></div></article>
</template>

<style scoped>
.product-card{min-width:0}.product-visual{position:relative;overflow:hidden;border:1px solid #e0eae7;border-radius:16px;background:#eef6f2}.product-visual>a{display:block;aspect-ratio:1/1}.product-visual img{display:block;width:100%;height:100%;object-fit:cover;transition:transform .35s}.product-card:hover .product-visual img{transform:scale(1.025)}.discount{position:absolute;left:10px;top:10px;padding:6px 8px;border-radius:7px;background:var(--ph-accent);color:#fff;font-size:9px;font-weight:900;text-transform:uppercase}.heart{position:absolute;right:9px;top:9px;display:grid;width:34px;height:34px;place-items:center;border:0;border-radius:50%;background:#fff;color:var(--ph-ink)}.product-copy{padding:13px 3px}.product-copy>span{color:var(--ph-primary);font:700 9px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.1em}.product-copy a{color:var(--ph-ink);text-decoration:none}.product-copy h3{min-height:40px;margin:7px 0 4px;font-size:14px;line-height:1.4}.product-copy>small{display:-webkit-box;overflow:hidden;color:#738681;font-size:11px;line-height:1.4;-webkit-box-orient:vertical;-webkit-line-clamp:2}.price-row{display:flex;align-items:end;justify-content:space-between;gap:10px;margin-top:13px}.price-row>div{display:grid}.price-row s{color:#83938f;font-size:10px}.price-row strong{font-family:"Trebuchet MS",sans-serif;font-size:18px;letter-spacing:-.03em}.price-row em{color:#71847f;font-size:9px;font-style:normal}.price-row button{display:grid;width:38px;height:38px;place-items:center;border:0;border-radius:10px;background:var(--ph-primary);color:#fff}.price-row button:disabled{cursor:not-allowed;opacity:.72}@media(max-width:560px){.product-copy h3{font-size:13px}.heart{display:none}.price-row strong{font-size:16px}}
</style>
