<script setup lang="ts">
import { Heart, ShoppingCart } from '@lucide/vue'
import type { StoreProduct, StorefrontPayload } from '#shared/types/storefront'
import { useStorefrontCatalog } from '~~/layers/storefront-core/app/composables/useStorefrontCatalog'
import { useStorefrontCommerce } from '~~/layers/storefront-core/app/composables/useStorefrontCommerce'
const props = defineProps<{ product: StoreProduct, storefront: StorefrontPayload }>()
const { money, productImage, usePlaceholder, discount } = useStorefrontCatalog(props.storefront)
const { addToCart, toggleWishlist, isWishlisted, busyProducts } = useStorefrontCommerce(props.storefront)
const wished = computed(() => isWishlisted(props.product.id))
const busy = computed(() => busyProducts.value.includes(props.product.id))
</script>

<template>
  <article class="retail-product card"><div class="product-media"><NuxtLink :to="`/produto/${product.slug}`"><img v-if="productImage(product)" :src="productImage(product)!" :alt="product.name" loading="lazy" @error="usePlaceholder"><img v-else src="/images/placeholders/product-default.png" alt="Imagem ilustrativa do produto" loading="lazy"></NuxtLink><span v-if="discount(product)" class="discount badge badge-secondary">-{{ discount(product) }}%</span><button type="button" class="favorite btn btn-circle btn-sm" :class="wished ? 'btn-secondary' : 'btn-ghost bg-base-100'" :aria-label="wished ? 'Remover da lista de desejos' : 'Adicionar à lista de desejos'" :aria-pressed="wished" @click="toggleWishlist(product)"><Heart :size="16" :fill="wished ? 'currentColor' : 'none'"/></button></div><div class="product-content"><span class="category">{{ product.categories[0]?.name || 'Cuidados diários' }}</span><NuxtLink :to="`/produto/${product.slug}`"><h3>{{ product.name }}</h3></NuxtLink><p>{{ product.excerpt || (product.stock > 0 ? `${product.stock} unidades disponíveis` : 'Produto indisponível') }}</p><div class="product-price"><span><s v-if="product.original_price && product.original_price > product.price">{{ money(product.original_price) }}</s><strong>{{ money(product.price) }}</strong><small>à vista</small></span><button type="button" class="btn btn-primary btn-sm" :disabled="product.stock<1 || busy" aria-label="Adicionar ao carrinho" @click="addToCart(product)"><span v-if="busy" class="loading loading-spinner loading-xs"></span><ShoppingCart v-else :size="16"/><em>{{ product.stock<1 ? 'Indisponível' : 'Adicionar' }}</em></button></div></div></article>
</template>

<style scoped>
.retail-product{display:flex;min-width:0;flex-direction:column;border:1px solid #dfe8e5;background:#fff;transition:border-color .2s,transform .2s}.retail-product:hover{border-color:#9dcabd;transform:translateY(-2px)}.product-media{position:relative;padding:14px}.product-media>a{display:block;aspect-ratio:1.2/1;overflow:hidden;background:#f7faf9}.product-media img{display:block;width:100%;height:100%;object-fit:contain;transition:transform .25s}.retail-product:hover img{transform:scale(1.035)}.discount{position:absolute;left:13px;top:13px;padding:5px 7px;border-radius:5px;background:var(--sf-accent);color:#fff;font-size:9px;font-weight:900}.favorite{position:absolute;right:16px;top:16px;display:grid;width:30px;height:30px;place-items:center;border:1px solid #e0e8e6;border-radius:50%;background:#fff;color:#607772}.product-content{display:flex;flex:1;flex-direction:column;padding:0 16px 15px}.category{color:#71847f;font-size:9px}.product-content>a{color:var(--sf-ink);text-decoration:none}.product-content h3{min-height:39px;margin:5px 0 2px;font-size:13px;line-height:1.45}.product-content p{min-height:28px;margin:0;color:#748681;font-size:9px;line-height:1.4}.product-price{display:flex;align-items:end;justify-content:space-between;gap:10px;margin-top:auto;padding-top:13px}.product-price>span{display:grid}.product-price s{color:#8a9996;font-size:9px}.product-price strong{color:var(--sf-primary);font-size:17px;font-variant-numeric:tabular-nums}.product-price small{color:#879692;font-size:8px}.product-price button{display:flex;height:34px;align-items:center;gap:6px;padding:0 10px;border:1px solid #a8d1c5;border-radius:6px;background:#eff9f5;color:var(--sf-primary);font-size:10px;font-weight:800}.product-price button:disabled{cursor:not-allowed;opacity:.75}.product-price em{font-style:normal}@media(max-width:560px){.product-media{padding:8px}.product-content{padding:0 10px 11px}.product-content h3{font-size:12px}.product-price{align-items:stretch;flex-direction:column}.product-price button{justify-content:center}.favorite{display:none}}
.retail-product{border-radius:12px;overflow:hidden}.retail-product:hover{box-shadow:0 14px 30px rgba(21,59,54,.08)}.product-media>a{border-radius:8px}.product-price button{min-height:34px}.favorite{border-color:transparent}.favorite[aria-pressed="true"]{color:#fff}
</style>
