<script setup lang="ts">
import { Headphones, LockKeyhole, PackageCheck, RefreshCcw, Tags, Truck } from '@lucide/vue'
import type { StorefrontTemplateBranding } from '#shared/types/template'
defineProps<{ storeName: string, theme: StorefrontTemplateBranding }>()
</script>

<template>
  <footer class="retail-footer"><section class="footer-benefits"><div><Tags/><span><strong>Preços justos</strong><small>Ofertas para sua rotina</small></span></div><div><Truck/><span><strong>Entrega para sua região</strong><small>Prazo calculado pelo CEP</small></span></div><div><LockKeyhole/><span><strong>Compra segura</strong><small>Seus dados protegidos</small></span></div><div><PackageCheck/><span><strong>Pedido acompanhado</strong><small>Do preparo à entrega</small></span></div><div><RefreshCcw/><span><strong>Compra tranquila</strong><small>Atendimento quando precisar</small></span></div></section><div class="footer-main"><div class="footer-brand"><span class="footer-symbol"></span><div><h2>{{ storeName }}</h2><small>{{ theme?.footer_tagline || 'cuidado todos os dias' }}</small></div><p>{{ theme?.footer_description || 'Sua farmácia online para encontrar medicamentos, higiene e bem-estar em um só lugar.' }}</p><strong><Headphones :size="18"/> {{ theme?.contact_phone || '(11) 3000-1234' }}</strong></div><nav><h3>Institucional</h3><NuxtLink to="/">Sobre a loja</NuxtLink><NuxtLink to="/categorias">Categorias</NuxtLink><NuxtLink to="/produtos">Todos os produtos</NuxtLink></nav><nav><h3>Minha conta</h3><NuxtLink to="/conta">Entrar ou cadastrar</NuxtLink><NuxtLink to="/conta/pedidos">Meus pedidos</NuxtLink><NuxtLink to="/conta/enderecos">Endereços</NuxtLink></nav><nav><h3>Atendimento</h3><NuxtLink to="/conta/pedidos">Acompanhar pedido</NuxtLink><span>Dúvidas frequentes</span><span>Política de entrega</span></nav><nav><h3>Informações</h3><span>Privacidade</span><span>Termos de uso</span><span>Política de cookies</span></nav></div><div class="footer-bottom"><span>© {{ new Date().getFullYear() }} {{ storeName }}. Todos os direitos reservados.</span><span>Comércio digital por Elinea</span></div></footer>
</template>

<style scoped>
.retail-footer{margin-top:55px;border-top:1px solid #e2e9e7;background:#fff;color:var(--sf-ink)}.footer-benefits{display:grid;grid-template-columns:repeat(5,1fr);width:min(100% - 40px,1400px);margin:auto;border-bottom:1px solid #e2e9e7}.footer-benefits>div{display:flex;align-items:center;justify-content:center;gap:10px;min-height:75px;color:var(--sf-primary)}.footer-benefits>div+div{border-left:1px solid #e2e9e7}.footer-benefits svg{width:21px}.footer-benefits span{display:grid;gap:3px}.footer-benefits strong{color:var(--sf-ink);font-size:9px}.footer-benefits small{color:#7d8e8a;font-size:8px}.footer-main{display:grid;grid-template-columns:1.3fr repeat(4,.7fr);gap:45px;width:min(100% - 40px,1400px);margin:auto;padding:55px 0}.footer-brand{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:10px}.footer-symbol{position:relative;display:block;width:38px;height:38px;border-radius:11px 11px 11px 3px;background:var(--sf-primary)}.footer-symbol:before,.footer-symbol:after{position:absolute;left:50%;top:50%;content:"";border-radius:2px;background:#fff;transform:translate(-50%,-50%)}.footer-symbol:before{width:21px;height:6px}.footer-symbol:after{width:6px;height:21px}.footer-brand h2{margin:0;font-size:19px;letter-spacing:-.04em}.footer-brand>div small{color:#81918d;font-size:7px;text-transform:uppercase;letter-spacing:.1em}.footer-brand p{grid-column:1/-1;max-width:290px;margin:12px 0;color:#697f7a;font-size:10px;line-height:1.6}.footer-brand>strong{grid-column:1/-1;display:flex;align-items:center;gap:7px;color:var(--sf-primary);font-size:12px}.footer-main nav{display:grid;align-content:start;justify-items:start;gap:10px}.footer-main h3{margin:0 0 7px;font-size:11px}.footer-main a,.footer-main nav span{color:#687d79;font-size:9px;text-decoration:none}.footer-main a:hover{color:var(--sf-primary)}.footer-bottom{display:flex;justify-content:space-between;width:min(100% - 40px,1400px);margin:auto;padding:20px 0;border-top:1px solid #e2e9e7;color:#84938f;font-size:8px}@media(max-width:900px){.footer-benefits{grid-template-columns:repeat(2,1fr)}.footer-benefits>div{justify-content:start;padding-left:20px}.footer-benefits>div:nth-child(odd){border-left:0}.footer-main{grid-template-columns:1.2fr repeat(2,1fr)}.footer-main nav:nth-last-child(-n+2){display:none}}@media(max-width:560px){.footer-benefits,.footer-main,.footer-bottom{width:min(100% - 24px,1400px)}.footer-benefits>div:nth-child(n+4){display:none}.footer-main{grid-template-columns:1fr 1fr}.footer-brand{grid-column:1/-1}.footer-main nav:nth-of-type(n+3){display:none}.footer-bottom{flex-direction:column;gap:7px}}
</style>
