<script setup lang="ts">
import { Heart, ShoppingCart } from '@lucide/vue'
import type { StoreProduct, StorefrontPayload } from '#shared/types/storefront'
import { useStorefrontCatalog } from '~~/layers/storefront-core/app/composables/useStorefrontCatalog'
import { useStorefrontCommerce } from '~~/layers/storefront-core/app/composables/useStorefrontCommerce'
const props = defineProps<{ product: StoreProduct, storefront: StorefrontPayload }>()
const { money, productImage, usePlaceholder, discount } = useStorefrontCatalog(props.storefront)
const { addToCart, toggleWishlist, isWishlisted, busyProducts } = useStorefrontCommerce(props.storefront)
const wished = computed(() => isWishlisted(props.product.id))
const busy = computed(() => busyProducts.value.includes(props.product.id))
</script>

<template>
  <article class="retail-product card"><div class="product-media"><NuxtLink :to="`/produto/${product.slug}`"><img v-if="productImage(product)" :src="productImage(product)!" :alt="product.name" loading="lazy" @error="usePlaceholder"><img v-else src="/images/placeholders/product-default.png" alt="Imagem ilustrativa do produto" loading="lazy"></NuxtLink><span v-if="discount(product)" class="discount badge badge-secondary">-{{ discount(product) }}%</span><button type="button" class="favorite btn btn-circle btn-sm" :class="wished ? 'btn-secondary' : 'btn-ghost bg-base-100'" :aria-label="wished ? 'Remover da lista de desejos' : 'Adicionar à lista de desejos'" :aria-pressed="wished" @click="toggleWishlist(product)"><Heart :size="16" :fill="wished ? 'currentColor' : 'none'"/></button></div><div class="product-content"><span class="category">{{ product.categories[0]?.name || 'Cuidados diários' }}</span><NuxtLink :to="`/produto/${product.slug}`"><h3>{{ product.name }}</h3></NuxtLink><p>{{ product.excerpt || (product.stock > 0 ? `${product.stock} unidades disponíveis` : 'Produto indisponível') }}</p><div class="product-price"><span><s v-if="product.original_price && product.original_price > product.price">{{ money(product.original_price) }}</s><strong>{{ money(product.price) }}</strong><small>à vista</small></span><button type="button" class="btn btn-primary btn-sm" :disabled="product.stock<1 || busy" aria-label="Adicionar ao carrinho" @click="addToCart(product)"><span v-if="busy" class="loading loading-spinner loading-xs"></span><ShoppingCart v-else :size="16"/><em>{{ product.stock<1 ? 'Indisponível' : 'Adicionar' }}</em></button></div></div></article>
</template>

<style scoped>
.retail-product{display:flex;min-width:0;flex-direction:column;border:1px solid rgba(21,59,54,.09);border-radius:15px;background:rgba(255,255,255,.9);box-shadow:0 18px 42px rgba(30,70,62,.07);overflow:hidden;transition:border-color .22s,box-shadow .22s,transform .22s}.retail-product:hover{border-color:rgba(31,107,79,.3);box-shadow:0 26px 58px rgba(30,70,62,.13);transform:translateY(-4px)}.product-media{position:relative;padding:12px}.product-media>a{display:block;aspect-ratio:1.08/1;overflow:hidden;border-radius:11px;background:linear-gradient(145deg,#f8faf8,#edf5f2)}.product-media img{display:block;width:100%;height:100%;object-fit:contain;transition:transform .28s}.retail-product:hover img{transform:scale(1.045)}.discount{position:absolute;left:16px;top:16px;padding:6px 8px;border-radius:7px;background:var(--sf-accent);color:#fff;font-size:10px;font-weight:900;box-shadow:0 10px 22px rgba(255,107,95,.22)}.favorite{position:absolute;right:17px;top:17px;display:grid;width:34px;height:34px;place-items:center;border:1px solid rgba(21,59,54,.08);border-radius:50%;background:rgba(255,255,255,.92);color:#607772;box-shadow:0 10px 24px rgba(30,70,62,.12)}.product-content{display:flex;flex:1;flex-direction:column;padding:3px 17px 17px}.category{color:#71847f;font-size:10px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.product-content>a{color:var(--sf-ink);text-decoration:none}.product-content h3{min-height:44px;margin:7px 0 5px;font-size:15px;font-weight:850;line-height:1.35;text-wrap:pretty}.product-content p{min-height:36px;margin:0;color:#748681;font-size:12px;line-height:1.45}.product-price{display:flex;align-items:end;justify-content:space-between;gap:10px;margin-top:auto;padding-top:16px}.product-price>span{display:grid}.product-price s{color:#8a9996;font-size:11px}.product-price strong{color:var(--sf-primary);font-size:22px;font-weight:950;font-variant-numeric:tabular-nums;letter-spacing:-.025em}.product-price small{color:#879692;font-size:10px}.product-price button{display:flex;height:38px;min-height:38px;align-items:center;gap:7px;padding:0 12px;border:1px solid rgba(31,107,79,.2);border-radius:9px;background:#eaf7f2;color:var(--sf-primary);font-size:12px;font-weight:900;transition:background .2s,transform .2s}.product-price button:hover:not(:disabled){background:var(--sf-primary);color:#fff;transform:translateY(-1px)}.product-price button:disabled{cursor:not-allowed;opacity:.75}.product-price em{font-style:normal}.favorite{border-color:transparent}.favorite[aria-pressed="true"]{color:#fff}@media(max-width:560px){.product-media{padding:8px}.product-content{padding:0 10px 12px}.product-content h3{font-size:13px}.product-content p{font-size:11px}.product-price{align-items:stretch;flex-direction:column}.product-price button{justify-content:center}.favorite{display:none}}
</style>
